_target_: src.models.posenet_module.PoseNetModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.01
  betas:
    - 0.9
    - 0.999
  weight_decay: 0.00001

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

num_landmarks: 23
heatmap_downsample: ${data.heatmap_downsample}
theta_bg: ${data.theta_bg}
theta_fg: ${data.theta_fg}
use_ic_loss: true

net:
  _target_: src.models.components.PoseNet.PoseNet
  num_landmarks: ${model.num_landmarks}

compile: false
