# @package _global_

defaults:
  - _self_
  - data: data
  - model: posenet_module
  - logger: wandb # or keep null if you don't use logger
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

task_name: "eval"

tags: ["eval", "posenet"]

# passing checkpoint path is necessary for evaluation
ckpt_path: "C:/Users/PC/OneDrive/Desktop/WORK/UET-VNU/TestPosenet/PoseNet/logs/train/runs/2025-03-10_22-38-16/checkpoints/epoch_026.ckpt"
